version: "3.8"


services:
    postgresql:
        container_name: postgresql
        image: postgres:14.5-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=USER
            - POSTGRES_PASSWORD=PASSWORD
            - POSTGRES_DB=DB
        networks:
            - custom


networks:
    custom:
        driver: bridge
