"""reorganization table

Revision ID: fc01062dfa51
Revises: 38db0c160054
Create Date: 2024-02-07 01:03:01.244267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc01062dfa51'
down_revision: Union[str, None] = '38db0c160054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('text', sa.String(), nullable=False))
    op.add_column('templates', sa.Column('entities', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=False))
    op.add_column('templates', sa.Column('keyboard', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text()), dimensions=2), nullable=False))
    op.drop_column('templates', 'from_chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('from_chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('templates', 'keyboard')
    op.drop_column('templates', 'entities')
    op.drop_column('templates', 'text')
    # ### end Alembic commands ###
