"""table reorganization

Revision ID: 27bfe10c4dff
Revises: fc01062dfa51
Create Date: 2024-02-09 15:52:47.192834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27bfe10c4dff'
down_revision: Union[str, None] = 'fc01062dfa51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.drop_column('templates', 'entities')
    op.drop_column('templates', 'media')
    op.drop_column('templates', 'keyboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('keyboard', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=False))
    op.add_column('templates', sa.Column('media', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('templates', sa.Column('entities', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=False))
    op.drop_column('templates', 'attachments')
    # ### end Alembic commands ###
